#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Convert a C/C++ array file generated by run_paddle_lite_conv.cc or npy_to_c.py
back to .npy.

Example:
  python3 c_array_to_npy.py output_data.cc output.npy --name OUTPUT
"""

import argparse
import re
from pathlib import Path

import numpy as np


C_TO_DTYPE = {
    "float": np.float32,
    "double": np.float64,
    "int8_t": np.int8,
    "uint8_t": np.uint8,
    "int16_t": np.int16,
    "uint16_t": np.uint16,
    "int32_t": np.int32,
    "uint32_t": np.uint32,
    "int64_t": np.int64,
    "uint64_t": np.uint64,
}


def strip_comments(s: str) -> str:
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    s = re.sub(r"//.*?$", "", s, flags=re.M)
    return s


def parse_numbers(block: str, dtype) -> np.ndarray:
    # The writer does not add float suffixes. Handle common C tokens anyway.
    cleaned = block
    cleaned = cleaned.replace("NAN", "nan").replace("nanf", "nan")
    cleaned = cleaned.replace("INFINITY", "inf").replace("Infinity", "inf")
    cleaned = cleaned.replace("infF", "inf").replace("inff", "inf")
    cleaned = re.sub(r"(?<=[0-9])([fFuUlL]+)\b", "", cleaned)
    cleaned = cleaned.replace("{", " ").replace("}", " ")
    cleaned = cleaned.replace("\n", " ")
    arr = np.fromstring(cleaned, sep=",", dtype=dtype)
    return arr


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("c_file", help="C/C++ file containing <NAME>_SHAPE and <NAME>_DATA")
    parser.add_argument("npy", help="output .npy path")
    parser.add_argument("--name", default="OUTPUT",
                        help="C symbol prefix, e.g. OUTPUT -> OUTPUT_DATA")
    args = parser.parse_args()

    text = Path(args.c_file).read_text(encoding="utf-8")
    text = strip_comments(text)
    name = args.name.upper()

    shape_re = re.compile(rf"{name}_SHAPE\s*\[[^\]]*\]\s*=\s*\{{(?P<body>.*?)\}}\s*;", re.S)
    shape_m = shape_re.search(text)
    if not shape_m:
        raise ValueError(f"Cannot find {name}_SHAPE in {args.c_file}")

    shape = [int(x.strip()) for x in shape_m.group("body").split(",") if x.strip()]
    if not shape:
        raise ValueError(f"{name}_SHAPE is empty")

    data_re = re.compile(
        rf"const\s+(?P<ctype>float|double|int8_t|uint8_t|int16_t|uint16_t|int32_t|uint32_t|int64_t|uint64_t)"
        rf"\s+{name}_DATA\s*\[[^\]]*\]\s*=\s*\{{(?P<body>.*?)\}}\s*;",
        re.S,
    )
    data_m = data_re.search(text)
    if not data_m:
        raise ValueError(f"Cannot find {name}_DATA in {args.c_file}")

    ctype = data_m.group("ctype")
    dtype = C_TO_DTYPE[ctype]
    arr = parse_numbers(data_m.group("body"), dtype=dtype)

    expected = int(np.prod(shape))
    if arr.size != expected:
        raise ValueError(f"Data size mismatch: parsed {arr.size}, expected {expected} from shape {shape}")

    arr = arr.reshape(shape)
    np.save(args.npy, arr)
    print(f"wrote: {args.npy}")
    print(f"dtype={arr.dtype}, shape={arr.shape}, size={arr.size}")


if __name__ == "__main__":
    main()
